/* Deletando registros com a clausula delete */

-- DELETE FROM CLIENTE;

SELECT * 
FROM CLIENTE;

SELECT COUNT(*)
FROM CLIENTE; -- ATUALMENTE 8 REGISTROS

SELECT COUNT(*)
FROM CLIENTE
WHERE NOME = 'MARCELA';

DELETE
FROM CLIENTE
WHERE NOME = 'MARCELA'; -- AGORA COM 7 REGISTROS

SELECT COUNT(*)
FROM CLIENTE;

--FIXAÇÃO

INSERT INTO CLIENTE VALUES('RAIMUNDA', 'F', 'RAIMUNDANA@GMAIL.COM', 151516170, '25252525', 'DIAMANTE - RIACHO ACIMA - DISNEYLANDIA - ES');

-- SEMPRE FAÇA UM SELECT PRIMEIRO
SELECT *
FROM CLIENTE
WHERE NOME = 'RAIMUNDA' AND EMAIL = 'RAIMUNDANA@GMAIL.COM';

-- APOS CONFERIR O RETORNO, DELETE
DELETE FROM
CLIENTE
WHERE NOME = 'RAIMUNDA' AND EMAIL = 'RAIMUNDANA@GMAIL.COM';