/* Atualizando valores utilizando Update */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'JOSE@GMAIL.COM'
WHERE NOME = 'JOSE';

UPDATE CLIENTE
SET TELEFONE = '39393939'
WHERE NOME = 'JOSE';

/* FIXACAO */

INSERT INTO CLIENTE(NOME) VALUES('RAIMUNDA');
INSERT INTO CLIENTE(NOME) VALUES('MARCELA');

UPDATE CLIENTE
SET SEXO = 'F', EMAIL = 'RAIMUNDA@GMAIL.COM', CPF = '151516169', TELEFONE = '26272530', ENDERECO = 'CRISTAL - CRISTAIINA - CRISTALANDIA - PB'
WHERE NOME = 'RAIMUNDA';

UPDATE CLIENTE
SET SEXO = 'F', EMAIL = 'MARCELA@GMAIL.COM', CPF = '151516200', TELEFONE = '96272540', ENDERECO = 'CRISTAL - CRISTAIINA - ESMERALANDIA - PB'
WHERE NOME = 'MARCELA';