/* DDL - DATA DEFINITION LANGUAGE */

USE COMERCIO;

SHOW TABLES;

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT
    , NOME_PRODUTO VARCHAR(30) NOT NULL
    , PRECO INT
    , FRETE FLOAT(10,2) NOT NULL
);

/*ALTER TABLE*/
-- ALTERANDO NOME DE UMA COLUNA - CHANGE

ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

/*MODIFY - ALTERANDO O TIPO*/

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/*ADICIONANDO COLUNAS*/
ALTER TABLE PRODUTO
ADD PESO FLOAT (10,2) NOT NULL;

/*APAGANDO UMA COLUNA*/
ALTER TABLE PRODUTO
DROP COLUMN PESO;

DESC PRODUTO;

/* ADICIONANDO UMA COLUNA NA ORDEM ESPECÍFICA */
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST;