/* DML - DATA MANIPULATION LANGUAGE */
-- INSERT
SELECT * 
FROM CLIENTE;

INSERT INTO CLIENTE VALUES(NULL,'PAULA', 'M', NULL, '714147741');
INSERT INTO CLIENTE VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 8);

/* FILTROS */
SELECT * 
FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE */

SELECT * 
FROM CLIENTE
WHERE IDCLIENTE = 8;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 8;

/* DELETE */

INSERT INTO CLIENTE VALUES(NULL,'XXX', 'M', NULL, 'XXXXXXXXXX');

SELECT * 
FROM CLIENTE;

DELETE FROM CLIENTE
WHERE IDCLIENTE = 9;