/* DDL - DATA DEFINITION LANGUAGE */

USE COMERCIO;

SHOW TABLES;

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT
    , NOME_PRODUTO VARCHAR(30) NOT NULL
    , PRECO INT
    , FRETE FLOAT(10,2) NOT NULL
);