/* JUNÇÃO - JOIN */

SELECT NOME, EMAIL, IDCLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

--PEGAR NOME, SEXO, BAIRRO, CIDADE

SELECT NOME, SEXO, BAIRRO, CIDADE --PROJECAO
FROM CLIENTE, ENDERECO --ORIGEM
WHERE IDCLIENTE = ID_CLIENTE; --JUNCAO

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE
AND SEXO = 'F';

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
    INNER JOIN ENDERECO
    ON IDCLIENTE = ID_CLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE --PROJECAO
FROM CLIENTE --ORIGEM
    INNER JOIN ENDERECO --JUNCAO
    ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; --SELECAO

--PEGAR NOME, SEXO, EMAIL, TIPO, NUMERO
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON IDCLIENTE = ID_CLIENTE;