/* PRIMEIRA FORMA NORMAL */

/* REGRAS
1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA;

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA;

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO REGISTRO COMO SENDO ÚNICO (CHAVE PRIMÁRIA)
*/