/* Operadores Lógicos */

/* OR - OU */

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'M' OR ENDERECO LIKE '%MG';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F' OR ENDERECO LIKE '%JABOTICATUBAS';

/* AND - E */

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%MG';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%JABOTICATUBAS';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%MG';