/* CRIANDO UM BANCO DE DADOS */ 
CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */
USE TERA;

/* CRIANDO A TABELA DE CLIENTES */
CREATE TABLE CLIENTE(
	  NOME VARCHAR(30)
	, SEXO CHAR(1)
	, EMAIL VARCHAR(30)
	, CPF INT(11)
	, TELEFONE VARCHAR(30)
	, ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */
SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* FORMA 01 - OMITINDO AS COLUNAS */
INSERT INTO CLIENTE  VALUES('PAIVA', 'M', 'PAIVA@GMAIL.COM', 975751616, '34343535', 'LIMOEIRA - FLORESTAL - BELO HORIZONTE - MG');
INSERT INTO CLIENTE  VALUES('SANDRA', 'F', 'SANDRA@GMAIL.COM', 975753416, '34343535', 'SILVEIRA - FLORESTAL - BELO HORIZONTE - MG');
INSERT INTO CLIENTE  VALUES('LEANDRO', 'M', 'LEANDRO@GMAIL.COM', 975751610, '34343535', 'JARDINS - FLORESTAL - BELO HORIZONTE - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */
INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('JOSE', 'M', 'SALESTIANO - ESTORIL - BELO HORIZONTE - MG', '323534140', 123456789);

/* FORMA 03 - INSERT COMPACTO  */
INSERT INTO CLIENTE  VALUES('MARIA', 'F', 'MARIA@GMAIL.COM', 975751610, '34343535', 'JABOTICABA - FRUTAL - JABOTICATUBAS - MG')
, ('SORIN', 'M', 'SORIN@GMAIL.COM', 975751610, '34343535', 'LOS HERMANOS - ARGENTINA - BELO HORIZONTE - MG');

/* O COMANDO SELECT */

SELECT NOW() AS DATA_HORA, 'PAIVA' AS DBA;

SELECT 'PAIVA';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME AS CLIENTE , SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

/*APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, CPF
FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, CPF
FROM CLIENTE
WHERE ENDERECO = 'MG';

/* UTILIZANDO O LIKE (RESULTADO VAZIO) */

SELECT NOME, SEXO 
FROM CLIENTE
WHERE ENDERECO LIKE 'MG';

/* CARACTER CORINGA % - > QUALQUER COISA */

SELECT NOME, SEXO
FROM CLIENTE
WHERE ENDERECO LIKE '%MG';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO LIKE '%MG';

SELECT NOME, SEXO, ENDERECO 
FROM CLIENTE
WHERE ENDERECO LIKE '%FLORESTAL%';

