USE COMERCIO;

--RELACAO 1X1
DESC CLIENTE;

--PRIMEIRA COLOCA É NULL PARA INDICAR AO SQL QUE ELE VAI AUTOINCREMENTAR
INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M','JOAO@GMAIL.COM', '1020304050');
INSERT INTO CLIENTE VALUES(NULL, 'CARLOS', 'M','CARLOS@GMAIL.COM', '1020304051');
INSERT INTO CLIENTE VALUES(NULL, 'ANA', 'F','ANA@GMAIL.COM', '1020304052');
INSERT INTO CLIENTE VALUES(NULL, 'CLARA', 'F',NULL, '1020304053');
INSERT INTO CLIENTE VALUES(NULL, 'JORGE', 'M','JORGE@GMAIL.COM', '1020304054');
INSERT INTO CLIENTE VALUES(NULL, 'CÉLIA', 'F','CELIA@GMAIL.COM', '1020304055');
INSERT INTO CLIENTE VALUES(NULL, 'DANIEL PAIVA', 'M','DANIELPAIVA@GMAIL.COM', '1020304056');

DESC ENDERECO;
INSERT INTO ENDERECO VALUES(NULL, 'RUA LAGOINHA', 'LAGOA', 'BELO HORIZONTE', 'MG', 1)
						,(NULL, 'RUA FLORESTA', 'FLORESTAL', 'BELO HORIZONTE', 'MG', 2)
						,(NULL, 'RUA DA BAHIA', 'CENTRO', 'BELO HORIZONTE', 'MG', 3)
						,(NULL, 'RUA DA LAPA', 'LAGOA', 'RIO DE JANEIRO', 'RJ', 4)
						,(NULL, 'RUA DO FLAMENGO', 'JARDINS', 'SAO PAULO', 'SP', 5)
						,(NULL, 'RUA DA PADROEIRA', 'MARIA', 'OURO PRETO', 'MG', 6);
INSERT INTO ENDERECO VALUES(NULL, 'RUA SETE', 'BURITIS', 'BELO HORIZONTE', 'MG', 7);

--RELACAO 1XN
DESC TELEFONE;

INSERT INTO TELEFONE VALUES(NULL, 'RES', '31313131', 1);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '32323232', 2);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '33333333', 3);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '91919191', 4);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '37373737', 7);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '97979797', 7);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '08001000', 2);